#!/usr/bin/env python3
from __future__ import annotations

import os
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
os.environ.setdefault("MPLCONFIGDIR", str(REPO_ROOT / ".mplconfig"))

import pandas as pd

DEFAULT_TUNED_REPORT_DIR = REPO_ROOT / "results" / "reports" / "thesis_tuned_all"
DEFAULT_CORE_REPORT_DIR = REPO_ROOT / "results" / "reports" / "thesis"
_report_dir_env = os.getenv("THESIS_REPORT_DIR")
if _report_dir_env:
    REPORT_DIR = Path(_report_dir_env)
else:
    REPORT_DIR = DEFAULT_TUNED_REPORT_DIR if DEFAULT_TUNED_REPORT_DIR.exists() else DEFAULT_CORE_REPORT_DIR
OUTPUT_DIR = REPO_ROOT / "thesis" / "tables" / "generated"

MODEL_NAME_MAP = {
    "xgb_raw": "XGB",
    "xgb_node2vec": "XGB+Node2Vec",
    "lstm": "LSTM",
    "gcn": "GCN",
    "gat": "GAT",
    "tgcn_static": "TGCN-static",
    "tgat_static": "TGAT-static",
}

FAMILY_MAP = {
    "xgboost": "XGB",
    "lstm": "LSTM",
    "gnn": "GNN",
}

CATEGORY_MAP = {
    "graph_feature": "Graph-feature",
    "non_graph": "Non-graph",
    "static_gnn": "Static GNN",
    "static_temporal_labeled": "Static temporal",
}

EDGE_MAP = {
    "node2vec_correlation": "n2v-corr",
    "corr+sector+granger": "corr+sec+gr",
    "corr_sector_granger": "corr+sec+gr",
    "corr": "corr",
    "sector": "sector",
    "granger": "granger",
    "none": "none",
}


def _load_csv(name: str) -> pd.DataFrame:
    path = REPORT_DIR / name
    if not path.exists():
        raise FileNotFoundError(f"Missing required report file: {path}")
    return pd.read_csv(path)


def _metric_col(df: pd.DataFrame) -> str:
    if "portfolio_sharpe_annualized" in df.columns:
        return "portfolio_sharpe_annualized"
    if "portfolio_sharpe_daily" in df.columns:
        return "portfolio_sharpe_daily"
    if "portfolio_sharpe" in df.columns:
        return "portfolio_sharpe"
    raise ValueError("No Sharpe metric column found in input data")


def _edge_label(value: object) -> str:
    edge = str(value).strip().lower()
    if not edge or edge in {"nan"}:
        return ""
    return EDGE_MAP.get(edge, edge.replace("_", "+"))


def _model_name_label(value: object) -> str:
    model = str(value).strip().lower()
    if not model or model in {"nan"}:
        return "Model"
    return MODEL_NAME_MAP.get(model, model.upper())


def _family_label(value: object) -> str:
    family = str(value).strip().lower()
    if not family or family in {"nan"}:
        return ""
    return FAMILY_MAP.get(family, family)


def _category_label(value: object) -> str:
    cat = str(value).strip().lower()
    if not cat or cat in {"nan"}:
        return ""
    return CATEGORY_MAP.get(cat, cat)


def _model_label(row: pd.Series) -> str:
    model = _model_name_label(row.get("model_name", ""))
    edge = _edge_label(row.get("edge_type", ""))
    label = model
    if edge and edge != "none":
        label = f"{label} ({edge})"
    return label


def _strip_tuning_suffix(label: object) -> str:
    text = str(label).strip()
    for suffix in ("_tuned_all", "_tuned"):
        if text.endswith(suffix):
            return text[: -len(suffix)]
    return text


def _run_tag_to_label(label: object) -> str:
    tag = _strip_tuning_suffix(label)
    if tag == "xgb_raw":
        return "XGB"
    if tag == "xgb_node2vec_corr":
        return "XGB+Node2Vec (corr)"
    if tag == "lstm":
        return "LSTM"
    if tag.startswith("gcn_"):
        edge = _edge_label(tag.replace("gcn_", "").replace("_only", ""))
        return f"GCN ({edge})" if edge else "GCN"
    if tag.startswith("gat_"):
        edge = _edge_label(tag.replace("gat_", "").replace("_only", ""))
        return f"GAT ({edge})" if edge else "GAT"
    if tag.startswith("tgcn_static_"):
        edge = _edge_label(tag.replace("tgcn_static_", "").replace("_only", ""))
        return f"TGCN-static ({edge})" if edge else "TGCN-static"
    if tag.startswith("tgat_static_"):
        edge = _edge_label(tag.replace("tgat_static_", "").replace("_only", ""))
        return f"TGAT-static ({edge})" if edge else "TGAT-static"
    return tag.replace("_", "-")


def _write_table(df: pd.DataFrame, out_name: str, caption: str, label: str) -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    tabular = df.to_latex(index=False, escape=True, float_format="%.4f")
    latex = (
        "\\begin{table}[htbp]\n"
        f"\\caption{{{caption}}}\n"
        f"\\label{{{label}}}\n"
        "\\centering\n"
        "\\small\n"
        "\\setlength{\\tabcolsep}{4pt}\n"
        "\\resizebox{\\textwidth}{!}{%\n"
        f"{tabular.rstrip()}\n"
        "}\n"
        "\\end{table}\n"
    )
    out_path = OUTPUT_DIR / out_name
    out_path.write_text("% Auto-generated by thesis/scripts/export_tables.py\n" + latex, encoding="utf-8")


def _export_top_models(master: pd.DataFrame) -> None:
    sharpe_col = _metric_col(master)
    for freq in (1, 5):
        subset = master.copy()
        if "rebalance_freq" in subset.columns:
            subset = subset[subset["rebalance_freq"] == freq]
        if subset.empty:
            continue

        subset = subset.sort_values(sharpe_col, ascending=False).head(8)
        family_col = subset["model_family"] if "model_family" in subset.columns else pd.Series([""] * len(subset), index=subset.index)
        table = pd.DataFrame(
            {
                "Model": subset.apply(_model_label, axis=1),
                "Family": family_col.map(_family_label),
                "Rank IC": subset.get("prediction_rank_ic", pd.NA),
                "Sharpe": subset.get(sharpe_col, pd.NA),
                "Max DD": subset.get("portfolio_max_drawdown", pd.NA),
                "Final": subset.get("portfolio_final_value", pd.NA),
            }
        )
        _write_table(
            table,
            out_name=f"top_models_reb{freq}.tex",
            caption=f"Top models by Sharpe (rebalance\\_freq={freq}).",
            label=f"tab:top-models-reb{freq}",
        )


def _export_family_summary(family: pd.DataFrame) -> None:
    sharpe_col = _metric_col(family)
    category_col = "category" if "category" in family.columns else "model_family"

    subset = family.copy()
    keep = [
        category_col,
        "rebalance_freq",
        "run_tag",
        "prediction_rank_ic",
        sharpe_col,
        "portfolio_final_value",
    ]
    keep = [col for col in keep if col in subset.columns]
    subset = subset[keep]
    subset = subset.rename(
        columns={
            category_col: "Category",
            "rebalance_freq": "Rebalance",
            "run_tag": "Model",
            "prediction_rank_ic": "Rank IC",
            sharpe_col: "Sharpe",
            "portfolio_final_value": "Final",
        }
    )
    if "Category" in subset.columns:
        subset["Category"] = subset["Category"].map(_category_label)
    if "Model" in subset.columns:
        subset["Model"] = subset["Model"].map(_run_tag_to_label)

    _write_table(
        subset,
        out_name="family_summary.tex",
        caption="Best runs by model category and rebalance policy.",
        label="tab:family-summary",
    )


def _export_edge_ablation(edge: pd.DataFrame) -> None:
    sharpe_col = _metric_col(edge)
    keep = [
        "rebalance_freq",
        "edge_type",
        "model_count",
        "prediction_rank_ic",
        sharpe_col,
        "portfolio_max_drawdown",
    ]
    keep = [col for col in keep if col in edge.columns]

    subset = edge[keep].rename(
        columns={
            "rebalance_freq": "Rebalance",
            "edge_type": "Edge",
            "model_count": "N",
            "prediction_rank_ic": "Mean IC",
            sharpe_col: "Mean Sharpe",
            "portfolio_max_drawdown": "Mean MDD",
        }
    )
    if "Edge" in subset.columns:
        subset["Edge"] = subset["Edge"].map(_edge_label)

    _write_table(
        subset,
        out_name="edge_ablation.tex",
        caption="Edge-type ablation summary from thesis report output.",
        label="tab:edge-ablation",
    )


def main() -> None:
    master = _load_csv("master_comparison.csv")
    family = _load_csv("family_summary.csv")
    edge = _load_csv("edge_ablation_summary.csv")

    _export_top_models(master)
    _export_family_summary(family)
    _export_edge_ablation(edge)

    print(f"Using report directory: {REPORT_DIR}")
    print(f"Wrote LaTeX tables to: {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
